analysis_task:
  description: >
    Conduct a thorough analysis about the {resume}. Focus on:
      - STAR methodology to show better your skills and experiences
      - Suggest improvements to the descriptions based on STAR methodology
      - Mark the information that needs to be double-checked for accuracy and clarity
      - Improve resume suggesting any relevant information
  expected_output: >
    A list with 10 bullet points of the most relevant information to improve the {resume}.
  agent: linkedin_recruiter
  output_file: "output/analysis.md"

resume_enhancer_task:
  description: >
    Analyze the analysis findings and rewrite the {resume} to improve it.
    The resume should:
      - Include key information from the analysis
      - Be well structured and easy to read
      - Provide STAR descriptions to show your skills and experiences.
      - Ensure the STAR descriptions are concise and clear.
      - STAR description should be written in a single paragraph/sentence.
  expected_output: >
    A rewritten resume based on the analysis findings. The structure of the resume should include:
      - Personal information
      - Skills
      - Languages
      - Interests
      - About
      - Experience
      - Education
      - Certifications
      - Projects
      - Achievements
  output_file: "output/resume.md"
  context:
    - analysis_task
  agent: resume_enhancer
